// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"week4/internal/myapp"
	"week4/internal/myapp/biz"
	"week4/internal/myapp/controller"
	"week4/internal/myapp/data"
	"week4/internal/myapp/service"
)

// Injectors from wire.go:

func initApp() (myapp.AppControllers, func(), error) {
	dataData, cleanup, err := data.NewData()
	if err != nil {
		return myapp.AppControllers{}, nil, err
	}
	helloRepo := data.NewHelloRepo(dataData)
	helloBiz := biz.NewHelloBiz(helloRepo)
	helloService := service.NewHelloService(helloBiz)
	helloController := controller.NewHelloController(helloService)
	appControllers := myapp.NewAppControllers(helloController)
	return appControllers, func() {
		cleanup()
	}, nil
}
